version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_chat
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local