version: '3.1'
services:
  test-db:
    image: postgres:16.1
    container_name: test-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test