server:
  port: 8081
spring:
  application:
    name: SharePlace
  security:
    user:
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
#security:
#  basic:
#    enable: false
#  jwt:
#    uri: /auth/**
#    header: Authorization
#    prefix: Bearer
#    expiration: 86400
#    secret: JwtSecretKey
logging:
  level:
    org:
      springframework:
        security: TRACE